server:
  port: 8081 # Сменили порт, чтобы не конфликтовать с Gateway (8080)
spring:
  application:
    name: learn-app
  config:
    import: "optional:configserver:http://localhost:8888/"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/